---
- name: Add SSH keys to authorized_keys
  hosts: all
  gather_facts: false
  tasks:
    - authorized_key:
        user: root
        key: "{{ item }}"
      loop:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWUKywCYJL60WYcPznHf+BYIqwCMmKhzIh/TC1U5pMuKv9/Q4whaTH5C5K4BSyaJZ/c5kl1YEjjB9XLP6xIcRKixE5xoKLu9bpeokZfrqvW9M+r2inA2pYwwVdId8BHsIkQyZ2yoX9zQVIhWHbpd32J1gQ1zme6Ip0G0Q/ihWd+ZxEW4JySJr0JT/tb3cm2+gLoDzn1D9j4yB6bXa7s4ivPdQtwqLrGerWI1GJvmunQUAozc1L6JrpvfXdwzKH8koSsfaBldrME3pEY2sHcpE2ZSI9i1JtRD01wl/QK2a4aXWYbaYDW/7rX5abhzOttDNen6YwNvFIq8iwVjItrHIp
# Generate SSH key using slu
#
#     slu ssh keygen
#
# -----BEGIN OPENSSH PRIVATE KEY-----
# b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
# NhAAAAAwEAAQAAAQEA1lCssAmCS+tFmHD85x3/gWCKsAjJiocyIf0wtVOaTLir/f0OMIWk
# x+QuSuAUsmiWf3OZJdWBI4wfVyz+sSHESosROcaCi7vW6XqJGX66r1vTPq9opwNqWMMFXS
# HfAR7CJEMmdsqF/c0FSIVh26Xd9idYENc5nuiKdBtEP4oVnfmcRFuCckia9CU/7W93Jtvo
# C6A859Q/Y+Mgem12u7OIrz3ULcKi6xnq1iNRib5rp0FAKM3NS+ia6b313cMyh/JKErH2gZ
# XazBN6RGNrB3KRNmUiPYtSbUQ9NcJf0CtmuGl1mG2mA1v+61+Wm4czrbQzXp+mMDbxSKvI
# sFYyLaxyKQAAA7hmtUGWZrVBlgAAAAdzc2gtcnNhAAABAQDWUKywCYJL60WYcPznHf+BYI
# qwCMmKhzIh/TC1U5pMuKv9/Q4whaTH5C5K4BSyaJZ/c5kl1YEjjB9XLP6xIcRKixE5xoKL
# u9bpeokZfrqvW9M+r2inA2pYwwVdId8BHsIkQyZ2yoX9zQVIhWHbpd32J1gQ1zme6Ip0G0
# Q/ihWd+ZxEW4JySJr0JT/tb3cm2+gLoDzn1D9j4yB6bXa7s4ivPdQtwqLrGerWI1GJvmun
# QUAozc1L6JrpvfXdwzKH8koSsfaBldrME3pEY2sHcpE2ZSI9i1JtRD01wl/QK2a4aXWYba
# YDW/7rX5abhzOttDNen6YwNvFIq8iwVjItrHIpAAAAAwEAAQAAAQAdnvTfN9E8cP4jfapW
# vzyrQw6oGe7RKLJzJC1xQmbXJ8cNycYGStJlllIXozT5G5+BahbGteWtZhaG0/83uDULII
# F2/MraSVIA3yDH104yInzl8xSB0OUH85xwLNhHrVqj7GwKix9N3uJWDali1GADP5jaawTZ
# w8YvGf2q0oj+VlrQZbtz8r3Zi9BdQe6ItbBFCF4yQCquwsq92xOrK6N+dygOYhnkKUD2VJ
# z3m5gK05wcS9ftC/9VttF9INBaYKf+8JRW46Buv93zE2vItfNc0b+SSytGfk/UmQoxCi3B
# SFQ8lDGTlDPDdpsqoa2EGuqlthCC+EtknILxZ0wGMBEhAAAAgQCefQqLOmCDTe0GmtSpdO
# Cry4qIGNs3+sIQ9uUU9jm3aHNxC1qsWP8AUECODFtDL4ppNhP2mRDjT8DGC59JvHKbPv0a
# 4yJ7F7UeZj/m8YQ/yQjJDPF63/667hp6ApMgvAnGdnmvN4PsBT6yKhXFKnKUdY2EBSHwcP
# ixQlsDf/ilWAAAAIEA7/Usj1YUNFAmDKOCfuA/kjcGSslGD/bCpMlnTUze9AMyjYCUCpBR
# oekVAL7PAFzOUpUCzJR91gx7QHxOvAvBb7WXIAcWFuq0qd0pYvpfI89fEbRnFk5k6z4QVp
# aGHqt+lu+BdvimOwPm/Vo+eFvs/bQejH89/hbLSQpUG/1Bel0AAACBAOSkohgzCP7o6O6j
# OefdlOcih+EzdZIXkD8ULGLMZfF7hwzdZJ/6YCKAQg4zUgIHtASV4ryiuzFX26/JSDf94u
# UdYqT6W9Wsy0PbO6V36jgFfMFX8bbJ3vjNcmxsc2d+TbA6PDfduQF4DPU9+1hoUbru73yU
# hI43XM8RZeziWtI9AAAAAAEC
# -----END OPENSSH PRIVATE KEY-----

# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWUKywCYJL60WYcPznHf+BYIqwCMmKhzIh/TC1U5pMuKv9/Q4whaTH5C5K4BSyaJZ/c5kl1YEjjB9XLP6xIcRKixE5xoKLu9bpeokZfrqvW9M+r2inA2pYwwVdId8BHsIkQyZ2yoX9zQVIhWHbpd32J1gQ1zme6Ip0G0Q/ihWd+ZxEW4JySJr0JT/tb3cm2+gLoDzn1D9j4yB6bXa7s4ivPdQtwqLrGerWI1GJvmunQUAozc1L6JrpvfXdwzKH8koSsfaBldrME3pEY2sHcpE2ZSI9i1JtRD01wl/QK2a4aXWYbaYDW/7rX5abhzOttDNen6YwNvFIq8iwVjItrHIp
