---
- name: Debug Example
  hosts: all
  gather_facts: false

  tasks:
    - name: Print message
      debug:
        msg: "Hello World!"
- name: Debug Example with facts
  hosts: all
  gather_facts: true

  tasks:
    - name: Print message
      debug:
        msg: "Hello World from {{ ansible_facts['hostname'] }}!"
