---
- name: Handlers Example
  hosts: all
  gather_facts: false

  tasks:
    - name: Create file foo
      copy:
        content: "Hello World\n"
        dest: /tmp/hello-foo
        owner: root
        group: root
        mode: 0644
      notify:
        - cat file

    - name: Create file bar
      copy:
        content: "Hello World\n"
        dest: /tmp/hello-bar
        owner: root
        group: root
        mode: 0644
      notify:
        - cat file

  handlers:
    - name: cat file
      shell:
        cmd: cat /tmp/hello-*
      register: cat_file
      notify:
        - debug

    - name: debug
      debug:
        msg: "{{ item }}"
      loop: "{{ cat_file.stdout_lines }}"
