---
- name: Setup Web Server
  hosts: all
  gather_facts: false
  vars:
    x_name: "{{ name | default('Ondrej') }}"
    x_server_name: "{{ server_name | default(None) }}"
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Copy index.html from template
      template:
        src: index3.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
