---
- name: Register Example with Template
  hosts: all

  tasks:
    - name: List of files and directories
      command: ls /
      register: content
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Copy index.html from template
      template:
        src: index.register.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
