---
- name: Remove Nginx
  hosts: all
  gather_facts: false
  tasks:
    - name: Stop Nginx Service
      service:
        name: nginx
        state: stopped
    - name: Remove Nginx
      apt:
        name: nginx
        state: absent
