---
- name: Wait for port 22
  hosts: all
  gather_facts: false

  tasks:
    - name: First message
      wait_for:
        port: 22

- name: Wait for port 8000
  hosts: all
  gather_facts: false

  tasks:
    - name: First message
      wait_for:
        port: 8000

- name: Wait for port 8000 to be stopped
  hosts: all
  gather_facts: false

  tasks:
    - name: First message
      wait_for:
        port: 8000
        state: stopped
